### ISSUE TITLE
Uncaught exception when upgrading past v2.5.5 to latest

### ISSUE THREAD

**Issue by lenaxia** [Tautulli/Tautulli#1436]
**Describe the Bug**
When upgrading to latest, startup fails with uncaught exception due to the library

**Steps to Reproduce**
1. docker-compose up
2. Observe failure
3. revert back to v2.5.5 and failure goes away
4. Backups of my database can be provided to aid in reproduction

**Expected Behavior**
tautulli to complete launch successfully and migrate to the new version

**Relevant Settings**
Docker Engine
```
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:05 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Docker-Compose.yml
```
version: "2"
services:
  tautulli:
    image: ghcr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TAUTULLI_DOCKER=True
    volumes:
      - /mnt/docker/tautulli:/config
      - "/mnt/plexdata/Library/Application Support/Plex Media Server/Logs/:/logs:ro"
    ports:
      - 8181:8181
    restart: unless-stopped
    networks:
      - medianet
      - t2_proxy
```

**Tautulli and System Info (see Tautulli settings page)**
- Version: [eg. v2.6.6]
- Git Branch: [eg. master]
- Git Commit Hash: [eg. 2cc5bf812fe05e0666aeaeb37ed550c59816fb4c]
- Platform and Version: [eg. Windows 10]
- Python Version: [e.g. 3.8.8]
- Browser and Version: [e.g. Chrome 88]

**Link to logs (required)**
https://gist.github.com/lenaxia/6a635487dc9b69d1b6103cc624f54fb3
