### ISSUE TITLE
Stay at authentication page

### ISSUE THREAD

**Issue by sbeaudoin** [Tautulli/Tautulli#1537]
### Describe the Bug

Latest docker image from ghcr.io/tautulli/tautulli:latest, recreated container brand new to try to solve the problem.  Authentication from plex or tautulli page bring me back to the authentication page.  Container log says "Admin use xxx logged into Tautulli using Plex OAuth Login".

### Steps to Reproduce

1. Install docker ghcr.io/tautulli/tautulli:latest with empty volume.  
2. Access the site and go through the setup process successfully.
3. Access the site again and authenticate by either method, plex or tautulli.
4. The authentification page is still displayed.

### Expected Behavior

Be redirected to the main tautulli page.

### Tautulli Version

Unknown, unable to access settings.

### Git Branch

Unknown, unable to access settings.

### Git Commit Hash

Unknown, unable to access settings.

### Platform and Version

Docker under ubuntu 20.

### Python Version

Unknown, unable to access settings.

### Browser and Version

Edge Chromium latest version on Windows 11.

### Link to Logs

https://gist.github.com/sbeaudoin/abab7d0a064529c4849d5c30493f6eef

**Comment by JonnyWong16** [comment]
How are you accessing Tautulli? IP address? Domain? With reverse proxy? In an iFrame?

**Comment by sbeaudoin** [comment]
Directly.  The container is configured to access tautulli web server with port 8081 and the docker server have a static IP and have a DNS entry named srvr-docker.  So, I access it from my Windows computer with edge chromium with "http://srvr-docker:8081".  Here is the content of the yaml file I used to create it with docker-compose :

```
version: "2.1"

services:
  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Montreal
    volumes:
      - /home/public/docker/volumes/tautulli:/config
    ports:
      - "8081:8181"
    restart: unless-stopped
    networks:
      - local-bridge

networks:
  local-bridge:
    external: true
    name: local-bridge
```
