### ISSUE TITLE
Tautilli refuses to verify the server even when it is accepted on the plex side

### ISSUE THREAD

**Issue by Salvora** [Tautulli/Tautulli#2567]
### Describe the Bug

Plex and Tautilli are hosted on the same machine
**Plex Settings:**
Secure Connections: Required
wildcard certificate installed on plex
custom certificate set: plex.domain.org

Tautilli is deployed with below compose:

```yaml
  tautulli:
    image: ghcr.io/tautulli/tautulli:latest
    container_name: tautulli
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      - PUID=${TAUTULLI_PUID}
      - PGID=${DOWNLOADERS_PGID}
      - TZ=Europe/Istanbul
    volumes:
      - /volume1/docker/downloaders/tautulli/config:/config
    ports:
      - 8181:8181
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "${PLEX_DOMAIN}:host-gateway"
    networks:
      - downloaders-network
    restart: unless-stopped
```
`PLEX_DOMAIN=plex.domain.org`
This is a workaround I use to skip the ssl verification if there is no such options present on the container side.

When I try to verify server, I see on Plex logs that connection gets accepted.
172.26.0.4 is the container ip address of Tautilli

```
Jun 21, 2025 08:47:05.348 [139964813880120] DEBUG - Request: [172.26.0.4:51718 (Subnet)] GET /identity (14 live) #3c73 TLS GZIP Signed-in
Jun 21, 2025 08:47:05.349 [139964941019960] DEBUG - Completed: [172.26.0.4:51718] 200 GET /identity (14 live) #3c73 TLS GZIP 0ms 487 bytes (pipelined: 1)
Jun 21, 2025 08:47:17.258 [139964813880120] DEBUG - Request: [172.26.0.4:51754 (Subnet)] GET /status/sessions (10 live) #3da0 GZIP Signed-in Token (nick)
Jun 21, 2025 08:47:17.528 [139964813880120] DEBUG - [Req#3da0] [Now] Adding 0 sessions.
Jun 21, 2025 08:47:17.528 [139964938910520] DEBUG - Completed: [172.26.0.4:51754] 200 GET /status/sessions (10 live) #3da0 GZIP 270ms 397 bytes (pipelined: 1)
Jun 21, 2025 08:47:17.534 [139964813880120] DEBUG - Request: [172.26.0.4:51756 (Subnet)] GET /:/websockets/notifications (10 live) #3dab Signed-in Token (nick)
Jun 21, 2025 09:25:44.155 [139964856666936] Debug — Request: [172.26.0.4:56446 (Subnet)] GET /identity (10 live) #5184 TLS GZIP Signed-in
Jun 21, 2025 09:25:44.156 [139964941019960] Debug — Completed: [172.26.0.4:56446] 200 GET /identity (10 live) #5184 TLS GZIP 0ms 487 bytes (pipelined: 1)
```

However, tautilli times out and does not verify the server.
Checking tautilli logs
```
<html>
<body>
<!--StartFragment-->
2025-06-21 09:21:05 | ERROR | Websocket connection test failed: [Errno 110] Connection timed out
-- | -- | --
2025-06-21 09:20:27 | ERROR | Websocket connection test failed: [Errno 110] Connection timed out
2025-06-21 09:19:43 | ERROR | Websocket connection test failed: [Errno 110] Connection timed out
2025-06-21 09:18:58 | DEBUG | Testing secure websocket connection...
2025-06-21 09:18:58 | INFO | Tautulli PlexTV :: Server URL retrieved.
2025-06-21 09:18:58 | INFO | Tautulli Config :: Writing configuration to file
2025-06-21 09:18:57 | INFO | Tautulli PlexTV :: Pinging Plex.tv to refresh token.
2025-06-21 09:18:57 | INFO | Tautulli PlexTV :: Requesting resources for server...
2025-06-21 09:18:57 | DEBUG | IP Checker :: Resolved plex.domain.org to 172.17.0.1.

<!--EndFragment-->
</body>
</html>
```

It is failing with the websocket connection.
However, Plex already accepts this websocket connection.

```
Jun 21, 2025 09:22:20.563 [139964792081208] DEBUG - Request: [172.26.0.4:56042 (Subnet)] GET /:/websockets/notifications (7 live) #50bc TLS Signed-in
Jun 21, 2025 09:22:20.564 [139964938910520] DEBUG - Completed: [172.26.0.4:56042] 401 GET /:/websockets/notifications (7 live) #50bc TLS 0ms 422 bytes (pipelined: 1)
```

### Steps to Reproduce

1. Set-up Plex SSL as described above
2. Deploy Tatulli as described above
3. Try to verify the server 

### Expected Behavior

should verify the server

### Tautulli Version

v2.15.2 

### Git Branch

master

### Git Commit Hash

76f6a2da6b3b394765203b7317cd97e7701a3067

### Platform and Version

[Docker] Linux 4.4.302+ (#72806 SMP Thu Sep 5 13:42:01 CST 2024 - Debian GNU/Linux 12 bookworm)

### Python Version

3.11.11 (main, Mar 17 2025, 23:23:20) [GCC 12.2.0]

### Browser and Version

Unrelated

### Link to Logs

https://gist.githubusercontent.com/Salvora/110e265e1d2f508dfe6ecfa2735fd331/raw/387932ec997c087f00f35c0a3e0cdbf8db3555e7/tautilli.log
